### ISSUE TITLE
TypeError: forward() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by ranran747** [TIGER-AI-Lab/AnyV2V#10]
I get an error when I click the 'run video editing' button in local_gradio_demo.
```
Traceback (most recent call last):
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 1945, in process_api
    result = await self.call_function(
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\blocks.py", line 1513, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\gradio\utils.py", line 831, in wrapper
    response = f(*args, **kwargs)
  File "D:\AnyV2V\gradio_demo.py", line 295, in btn_infer_fn
    result_video_path = AnyV2V_Editor.perform_anyv2v(video_path=video_path,
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AnyV2V\gradio_demo.py", line 186, in perform_anyv2v
    edited_video = self.pipe.sample_with_pnp(
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AnyV2V\i2vgen-xl\pipelines\pipeline_i2vgen_xl.py", line 1146, in sample_with_pnp
    noise_pred = self.unet(
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\diffusers\models\unets\unet_i2vgen_xl.py", line 694, in forward
    sample = upsample_block(
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\diffusers\models\unets\unet_3d_blocks.py", line 808, in forward
    hidden_states = resnet(hidden_states, temb)
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\AnyV2V\i2vgen-xl\pnp_utils.py", line 78, in forward
    hidden_states = self.conv1(hidden_states, scale) if not USE_PEFT_BACKEND else self.conv1(hidden_states)
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\pulle\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
```

**Comment by vinesmsuic** [comment]
likely the diffusers version issue. Please try with
```shell
pip install diffusers==0.26.3
```

**Comment by ranran747** [comment]
It worked. Thank you.

**Comment by LUOMIA** [comment]
Hi！I encounterd this question, if I use diffusers==0.26.3, what kind of huggingface-hub shoule I use? Now I have this question:

Traceback (most recent call last):
  File "/homedata/myluo/codes/AnyV2V/gradio_demo_style.py", line 16, in <module>
    from black_box_image_edit.instantstyle import InstantStyle
  File "/homedata/myluo/codes/AnyV2V/black_box_image_edit/__init__.py", line 1, in <module>
    from .instructpix2pix import InstructPix2Pix, MagicBrush
  File "/homedata/myluo/codes/AnyV2V/black_box_image_edit/instructpix2pix.py", line 4, in <module>
    from diffusers import StableDiffusionInstructPix2PixPipeline, EulerAncestralDiscreteScheduler
  File "/homedata/myluo/anaconda3/envs/anyv2v-i2vgen-xl/lib/python3.9/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/homedata/myluo/anaconda3/envs/anyv2v-i2vgen-xl/lib/python3.9/site-packages/diffusers/utils/__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/homedata/myluo/anaconda3/envs/anyv2v-i2vgen-xl/lib/python3.9/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/homedata/myluo/anaconda3/envs/anyv2v-i2vgen-xl/lib/python3.9/site-packages/huggingface_hub/__init__.py)

**Comment by vinesmsuic** [comment]
cached_download no longer exists on hugging face 
https://github.com/TencentARC/InstantMesh/issues/169
